# Generated by Django 2.2.4 on 2019-09-21 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Proprietaire',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nom', models.CharField(max_length=30)),
                ('Prenom', models.CharField(max_length=30)),
                ('Telephone', models.CharField(max_length=35)),
                ('Nombre_De_Piece', models.IntegerField()),
                ('Adresse', models.CharField(max_length=50)),
                ('Cout', models.IntegerField()),
                ('Image', models.ImageField(blank=True, null=True, upload_to='')),
                ('Description', models.TextField(max_length=900)),
                ('Duree', models.IntegerField()),
                ('Genre', models.CharField(max_length=30)),
                ('Departement', models.CharField(max_length=35)),
                ('Date_du_jour', models.DateField()),
                ('Sexe', models.CharField(max_length=20)),
                ('Longitude', models.DecimalField(decimal_places=30, max_digits=30)),
                ('Latitude', models.DecimalField(decimal_places=30, max_digits=30)),
            ],
            options={
                'ordering': ('Nom',),
            },
        ),
        migrations.CreateModel(
            name='Utilisateur',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nom', models.CharField(max_length=35)),
                ('Prenom', models.CharField(max_length=35)),
                ('Sexe', models.CharField(max_length=35)),
                ('Pseudo', models.CharField(max_length=35)),
                ('Password', models.CharField(max_length=35)),
                ('Droit', models.CharField(max_length=35)),
                ('Date', models.DateField()),
            ],
            options={
                'ordering': ('Nom',),
            },
        ),
    ]
