# Generated by Django 2.2.4 on 2019-09-24 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Andou_Kay', '0003_auto_20190921_1855'),
    ]

    operations = [
        migrations.AddField(
            model_name='proprietaire',
            name='type',
            field=models.CharField(default='DEFAULT VALUE2', max_length=30),
        ),
    ]
