# Generated by Django 2.2.4 on 2019-09-24 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Andou_Kay', '0004_proprietaire_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='proprietaire',
            name='Genre',
        ),
        migrations.AddField(
            model_name='proprietaire',
            name='Monnaie',
            field=models.CharField(default='new value', max_length=30),
        ),
        migrations.AlterField(
            model_name='proprietaire',
            name='Duree',
            field=models.CharField(max_length=40),
        ),
    ]
