# Generated by Django 2.2.4 on 2019-09-24 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Andou_Kay', '0005_auto_20190923_2247'),
    ]

    operations = [
        migrations.AddField(
            model_name='proprietaire',
            name='Nif',
            field=models.CharField(default='DEFAULT Nif', max_length=30),
        ),
        migrations.AlterField(
            model_name='proprietaire',
            name='Monnaie',
            field=models.CharField(default='Monnaie value', max_length=30),
        ),
    ]
